title: Aries Chen's Homepage
page-top-title: Aries Chen
top-section-bg-text: Exploring the Future of AI
home-subtitle: Aries Chen&ensp;|&ensp;陈曈
copyright-text: '&copy; Aries Chen 2023-2025. All Rights Reserved.'
